export const rows = [
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
    {
        orderNumber: '1001',
        businessName: 'Move in & out',
        consumerName: 'Jamal Kerrod',
        placedAt: '02-02-2023',
        service: 'Cleaning',
        subCategory: 'House Cleaning',
        price: '$40',
        verification: 'Approved',
        status: 'Active',
        quote: 'View',

        business: 'XYZ',
        category: 'XYZ',
        subcategory: 'XYZ',
        phone: '+90 123 456 798',
        plan: '1 mo Pro',
        email: 'businessuser@gmail.com',
        url: './../assets/images/site/company-logo.png'
    },
];
